//
//  RCClipboardPrivacyGateTests.m
//  RevclipTests
//
//  Copyright (c) 2024-2026 Revclip. Licensed under the MIT License.
//

#import <XCTest/XCTest.h>

#import "RCClipboardService.h"
#import "RCClipData.h"
#import "RCPrivacyService.h"

@interface RCPrivacyService (Testing)
- (RCClipboardAccessState)accessStateByMappingPasteboardAccessBehavior:(NSInteger)behavior
                                                 privacyAPIAvailable:(BOOL)privacyAPIAvailable;
- (BOOL)shouldCaptureClipboardContentsForAccessState:(RCClipboardAccessState)state;
- (void)presentClipboardAccessGuidanceIfNeeded;
@end

@interface RCClipboardService (Testing)
- (BOOL)canReadPasteboardContentsUsingPrivacyGate;
- (RCClipData *)readEligibleClipFromPasteboard:(NSPasteboard *)pasteboard sourceBundleIdentifier:(NSString *)bundleIdentifier;
- (void)captureCurrentClipboardOnMonitoringQueue;
- (void)processClipDataOnMonitoringQueue:(RCClipData *)clipData
                  sourceBundleIdentifier:(NSString *)sourceBundleIdentifier;
@end

@interface RCStubPrivacyService : RCPrivacyService
@property (nonatomic, assign) BOOL captureAllowed;
@property (nonatomic, assign) NSInteger guidanceCallCount;
@end

@implementation RCStubPrivacyService

- (BOOL)shouldCaptureClipboardContents {
    return self.captureAllowed;
}

- (void)showClipboardAccessGuidance {
}

- (void)presentClipboardAccessGuidanceIfNeeded {
    self.guidanceCallCount += 1;
}

@end

@interface RCTestClipboardService : RCClipboardService
@property (nonatomic, assign) NSInteger processClipCallCount;
@property (nonatomic, assign) BOOL excludeSource;
@end

@implementation RCTestClipboardService
- (BOOL)sourceIsExcluded:(NSString *)bundleIdentifier { return self.excludeSource; }

- (void)processClipDataOnMonitoringQueue:(RCClipData *)clipData
                  sourceBundleIdentifier:(NSString *)sourceBundleIdentifier {
    (void)clipData;
    (void)sourceBundleIdentifier;
    self.processClipCallCount += 1;
}

@end

// Declared-only markers have no payload. Any attempt to read contents fails this test.
@interface RCMetadataOnlyPasteboard : NSObject
@property (nonatomic, copy) NSArray<NSString *> *types;
@property (nonatomic) NSInteger changeCount;
@end
@implementation RCMetadataOnlyPasteboard
- (NSData *)dataForType:(NSString *)type { XCTFail(@"Confidential clipboard contents were read"); return nil; }
- (id)forwardingTargetForSelector:(SEL)selector { XCTFail(@"Unexpected clipboard read: %@", NSStringFromSelector(selector)); return nil; }
@end

@interface RCClipboardPrivacyGateTests : XCTestCase
@end

@implementation RCClipboardPrivacyGateTests

- (void)testDeclaredConfidentialMarkersBlockReadsEvenWithoutPayload {
    RCTestClipboardService *service = [RCTestClipboardService new];
    for (NSString *marker in @[@"org.nspasteboard.ConcealedType", @"org.nspasteboard.TransientType", @"org.nspasteboard.AutoGeneratedType"]) {
        RCMetadataOnlyPasteboard *pasteboard = [RCMetadataOnlyPasteboard new];
        pasteboard.types = @[NSPasteboardTypeString, marker];
        XCTAssertNil([service readEligibleClipFromPasteboard:(NSPasteboard *)pasteboard sourceBundleIdentifier:@"example.app"]);
    }
}

- (void)testExcludedSourceBlocksReadsBeforeInspectingContent {
    RCTestClipboardService *service = [RCTestClipboardService new];
    service.excludeSource = YES;
    RCMetadataOnlyPasteboard *pasteboard = [RCMetadataOnlyPasteboard new];
    pasteboard.types = @[NSPasteboardTypeString];
    XCTAssertNil([service readEligibleClipFromPasteboard:(NSPasteboard *)pasteboard sourceBundleIdentifier:@"example.excluded"]);
}

- (RCPrivacyService *)makePrivacyService {
    return [[RCPrivacyService alloc] init];
}

- (void)testAccessBehaviorMappingWhenPrivacyAPIUnavailableTreatsAccessAsGranted {
    RCPrivacyService *service = [self makePrivacyService];

    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:NSPasteboardAccessBehaviorAlwaysDeny
                                                   privacyAPIAvailable:NO],
                   RCClipboardAccessStateGranted);
}

- (void)testAccessBehaviorMappingOnMacOS154 {
    RCPrivacyService *service = [self makePrivacyService];

    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:NSPasteboardAccessBehaviorDefault
                                                   privacyAPIAvailable:YES],
                   RCClipboardAccessStateNotDetermined);
    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:NSPasteboardAccessBehaviorAsk
                                                   privacyAPIAvailable:YES],
                   RCClipboardAccessStateNotDetermined);
    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:NSPasteboardAccessBehaviorAlwaysAllow
                                                   privacyAPIAvailable:YES],
                   RCClipboardAccessStateGranted);
    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:NSPasteboardAccessBehaviorAlwaysDeny
                                                   privacyAPIAvailable:YES],
                   RCClipboardAccessStateDenied);
    XCTAssertEqual([service accessStateByMappingPasteboardAccessBehavior:99
                                                   privacyAPIAvailable:YES],
                   RCClipboardAccessStateUnknown);
}

- (void)testShouldCaptureAllowsGrantedAndNotDeterminedButNotDeniedOrUnknown {
    RCPrivacyService *service = [self makePrivacyService];

    XCTAssertTrue([service shouldCaptureClipboardContentsForAccessState:RCClipboardAccessStateGranted]);
    XCTAssertTrue([service shouldCaptureClipboardContentsForAccessState:RCClipboardAccessStateNotDetermined]);
    XCTAssertFalse([service shouldCaptureClipboardContentsForAccessState:RCClipboardAccessStateDenied]);
    XCTAssertFalse([service shouldCaptureClipboardContentsForAccessState:RCClipboardAccessStateUnknown]);
}

- (void)testDeniedPrivacySkipsClipboardCapture {
    RCTestClipboardService *clipboard = [[RCTestClipboardService alloc] init];
    RCStubPrivacyService *privacy = [[RCStubPrivacyService alloc] init];
    privacy.captureAllowed = NO;
    [clipboard setValue:privacy forKey:@"privacyService"];

    XCTAssertFalse([clipboard canReadPasteboardContentsUsingPrivacyGate]);

    [clipboard captureCurrentClipboardOnMonitoringQueue];

    XCTAssertEqual(clipboard.processClipCallCount, 0);
    XCTAssertEqual(privacy.guidanceCallCount, 1);
}

- (void)testAllowedPrivacyOpensPasteboardReadGate {
    RCTestClipboardService *clipboard = [[RCTestClipboardService alloc] init];
    RCStubPrivacyService *privacy = [[RCStubPrivacyService alloc] init];
    privacy.captureAllowed = YES;
    [clipboard setValue:privacy forKey:@"privacyService"];

    XCTAssertTrue([clipboard canReadPasteboardContentsUsingPrivacyGate]);
    XCTAssertEqual(privacy.guidanceCallCount, 0);
}

@end
